FROM python:3.10-slim

WORKDIR /app

# Copier les dépendances
COPY requirements-api.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements-api.txt

# Copier le code de l'API
COPY api.py .

# Exposer le port de l'API
EXPOSE 8000

# Lancer l'API
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
